export default {
  none: 'None',
  black: 'Black',
  white: 'White',
  grey: 'Grey',
  brown: 'Brown',
  red: 'Red',
  orange: 'Orange',
  yellow: 'Yellow',
  green: 'Green',
  blue: 'Blue',
  purple: 'Purple',
  pink: 'Pink',
  multicolored: 'Multicolored',
};
